[package]
name = "simple-shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.29.0"
ctrlc = "3.4.7"
io = "0.0.2"
once_cell = "1.21.3"
prelude = "0.2.1"
thread = "0.0.1"
